### ISSUE TITLE
Small mistake in the draft report?

### ISSUE THREAD

**Issue by ineol** [YaZko/acm-climate#1]
Thank you for this great work!

I think I have found a small mistake in the draft. In section 3.2 [1], it is written that the conference with the lowest average per-participant carbon emission is PLDI'18 in Philadelphia with 0.9, but ICFP'12 and ICFP'14 are lower at 0.88.

(this comes from the draft at Yannick's web page)

[1] `https://github.com/YaZko/acm-climate/blob/master/paper/sigplan_climate/footprint.tex#L108`

**Comment by YaZko** [comment]
Hi @ineol,

Thanks a lot for catching this error, and for your interest in the project!
I just pushed a small change to fix this in the TeX.

Don't hesitate to open issues, contact us directly, or post on the acm-climate mailing list if you have any remarks, comments or desires to get involved :)

Best,
Yannick
