### ISSUE TITLE
Countries with spaces

### ISSUE THREAD

**Issue by markuswagnergithub** [YaZko/acm-climate#15]
Hi! 

What do I have to do to get countries like New Zealand and South Korea to work? United Kingdom seems fine, and so are the United States. Thank you! :)

Example entry: 
```
Looking for GPS coordinates of Seoul
'NoneType' object has no attribute 'alpha_2'
WARNING: in the list of participants, entry Data: (20170105,Seoul,None,South Korea,GECCO,2017) cannot be processed and has been ignored
```

**Comment by YaZko** [comment]
Hello,

As far as I can tell, there _should_ not be anything particular to be done, I have processed locations both from South Korea and New Zealand without issues.

I have tried to reproduce your bug, but the entry that you provided is processed without problem on my side.

The error "NoneType object has no attribute 'alpha_2'" is the surprising bit: if I'm not mistaken, it somehow means that the country field of the location contains None when the iso is attempted to be computed, where it should contain "South Korea".
The only thing I can think of would be that your cache (in 'input/.location_cache.csv') might contain unsafe data.
I suspect that I'm being a bit careless and that if an entry lacks the country field, I might log it before realizing it's unsafe.

I will keep thinking about it as I might be missing something: I had to put this project on the side for a bit this first half of the year, and therefore the code is not completely fresh in my mind at the moment. 

I can for now offer the following two options:
* either on your side give a shot at resetting your cache to the one on the repo, and see if it fixes your issue. However that will mean that all new locations that you had processed will have to be reprocessed.
* or I would be happy to try to process your whole data on my side to see if it reproduces the bug (in which case please contact me by email for this purpose).

Best

**Comment by markuswagnergithub** [comment]
Regarding the two options:
- resetting cache: already done this.
- I'll email you the data in the next minutes...

**Comment by markuswagnergithub** [comment]
closing, as it seems to be a (reproducible) glitch on my system.
