### ISSUE TITLE
Differentiating West Coast from East Coast in North America

### ISSUE THREAD

**Issue by YaZko** [YaZko/acm-climate#3]
North America is big enough and has sufficiently many researchers that working at a finer grained level than just "North America" could be beneficial.

It should essentially reduce to hard coding a list of US states and Canadian Counties that we judge as being "west".

(Following @ineol's suggesting)

**Comment by bcpierce00** [comment]
People have all sorts of different opinions about which states are “west” — it’s a question with a lot of historical baggage.  But a reasonable approximation is just to draw a line down the middle.  Probably doesn’t matter much exactly where for present purposes.

   - B
